"""empty message

Revision ID: c23e08555462
Revises: 08559e3b1341
Create Date: 2025-09-20 07:58:28.980404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c23e08555462'
down_revision: Union[str, Sequence[str], None] = '08559e3b1341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('duration', sa.Integer(), nullable=True))
    op.add_column('video', sa.Column('path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'path')
    op.drop_column('video', 'duration')
    # ### end Alembic commands ###
