"""empty message

Revision ID: 78e910cb63e1
Revises: c68e93fcf69f
Create Date: 2025-09-22 16:53:55.625516

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "78e910cb63e1"
down_revision: Union[str, Sequence[str], None] = "c68e93fcf69f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("video_statistic", sa.Column("chunks", sa.JSON(), nullable=False))
    op.add_column(
        "video_statistic", sa.Column("diff_chunks", sa.JSON(), nullable=False)
    )
    op.add_column(
        "video_statistic", sa.Column("chunk_size", sa.Integer(), nullable=False)
    )
    op.drop_column("video_statistic", "stats")
    op.drop_column("video_statistic", "diff_stats")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "video_statistic", sa.Column("diff_stats", sqlite.JSON(), nullable=False)
    )
    op.add_column("video_statistic", sa.Column("stats", sqlite.JSON(), nullable=False))
    op.drop_column("video_statistic", "chunk_size")
    op.drop_column("video_statistic", "diff_chunks")
    op.drop_column("video_statistic", "chunks")
    # ### end Alembic commands ###
